AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  update-trigger

Globals:
  Function:
    Timeout: 30
    PermissionsBoundary: !Sub "arn:aws:iam::${AWS::AccountId}:policy/holidays-jp-permissions-boundary-ap-northeast-1"

Resources:
  TriggerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: trigger/
      Handler: trigger
      Runtime: provided.al2023
      Architectures: [arm64]
      Events:
        Schedule:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: "rate(1 day)"
            Description: Create a repository dispatch event for https://github.com/shogo82148/holidays-jp
            Input: '{"owner":"shogo82148","repo":"holidays-jp","event_type":"update"}'
            PermissionsBoundary: !Sub "arn:aws:iam::${AWS::AccountId}:policy/holidays-jp-permissions-boundary-ap-northeast-1"
      Environment:
        Variables:
          GITHUB_API: https://api.github.com
          GITHUB_TOKEN: /github-actions/token
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: github-actions/token
