name: reviewdog
on: [pull_request]

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@c76cceaaab89abe74e649d2e34c6c9adc26662d2 # v2.10.0
        with:
          reporter: github-pr-review
          level: warning
          workdir: ./holidays-api/

  actionlint:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: reviewdog/action-actionlint@d63ba7532e0942965320cd8d73cbae4c7b3c5283 # v1.73.1
        with:
          reporter: github-pr-review
          level: warning

  cfn-lint:
    name: cfn-lint
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: shogo82148/actions-cfn-lint@8da0f97ab06c78ddf7748741082a1f583578e807 # v4.70.0
        with:
          reporter: github-pr-review
          level: warning
